### ISSUE TITLE
Where does this plugin stored logs in wordpress ?

### ISSUE THREAD

**Issue by farhan-differenz** [Prospress/wcs-action-scheduler-timeout-monitor#2]
I have install this plugin but i have to check where this plugin stored log so i can debug the issue.

**Comment by rrennick** [comment]
It logs to your WP debug log.

**Comment by farhan-differenz** [comment]
> It logs to your WP debug log.

It was very helpful if you can guide me which format did this plugin store log in WP debug log. I have checked in WP debug log there lots of warning message logged so bit easier to understand if any error stored from this plugin then this would be the format.

**Comment by rrennick** [comment]
It logs a record in the format of

`Scheduled action 1234 was about to timeout after X`

**Comment by farhan-differenz** [comment]
> It logs a record in the format of
> 
> `Scheduled action 1234 was about to timeout after X`

Subscription payment this plugin is giving exact error in woocommerce error log, i want to know where this 300 second taking time.Currently i dont see anything recorded about this. Will you please guide more in detail

**Comment by rrennick** [comment]
If you are using https://woocommerce.com/products/woocommerce-subscriptions/ contact support at https://woocommerce.com/contact-us/ .

I'm closing the issue a Github is for reporting bugs vs being a support portal.
